version: '3'
services:
  nginx:
    image: nginx:latest
    restart: always
    container_name: remote_hosts
    volumes:
      - ./hostsfile:/usr/share/nginx/html:ro
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 4567:80
