version: '3'
services:
  cogpt-api:
    image: geniucker/cogpt:latest
    environment:
      - HOST=0.0.0.0
    ports:
      - 3333:8080
    volumes:
      - ./db:/app/db
      - ./log:/app/log
    restart: always
    container_name: cogpt-api

  chatgpt-next-web:
    image: yidadaa/chatgpt-next-web
    restart: always
    ports:
      - "0.0.0.0:3000:3000"
    depends_on:
      - cogpt-api
    container_name: chatgpt-next-web
